### PR TITLE
Pakyow issue 78 r

### PR DESCRIPTION
**Pull request by jphager2**
An example of one way to execute instructions for attributes to update nodes in bindAttributesToNode.  Works with the two instructions, `insert` and `remove`, from the issue-78 branch of pakyow.

Tested with class attribute.

### CODE REVIEW

**Comment by bryanp** [comment]
I think I need more context here. It looks like the previous implementation was at least trying to do the right thing by calling `setAttr`. Can you explain why that wasn't working? In general I think the approach you're taking could lead to a reimplementation of most of the attribute stuff already present, which I'd like to avoid if possible.

**Comment by jphager2** [comment]
So setAttr simply calls setAttribute on the node. So somewhere along the
way attribute values from the payload need to be checked if they contain
instructions, and then from the instructions, initialize and call the right
pw_attrs method.

I think maybe the confusion is steming from the payload structure, which I
am still not certain about. Comparing ui_view.rb and pakyow.js, I feel that
pakyow.js origionally was designed to recieve a top level instruction with
the "attrs" key. But I'm not sure that even that was handled yet.

Anyway, I agree that the structure that exists should be used. I think it
is just a matter of harmonizing the payload with what pakyow.js expects and
then maybe connect a few dots.

**Comment by bryanp** [comment]
Yep, that makes more sense now. As you say, we should work on getting the payload correct. For discussions sake, can you paste an example payload that's being generated on the backend as of now?

**Comment by jphager2** [comment]
```
(0ce34a634c561c38221b6a39c7e4d0af0646bb21): sending message {:payload=>[[:apply, [{"id"=>17, "title"=>"Baltimore Greenway to the Chesapeake Bay", "body"=>"**Baltimore's Greenway to the Chesapeake Bay**\r\n- Download or listen to an \r\n[audio tour](http://urbantells.net/gwynnsfalls)\r\non the Gwynns Falls Trail with trail historian \r\nEd Orser and audio artist Steve Bradley.", "slug"=>"", "published_on"=>Mon, 01 Jun 2015, "created_at"=>2015-06-01 11:16:11 UTC, "updated_at"=>2015-06-29 06:00:57 UTC, :markup_body=>{:content=>"<p><strong>Baltimore&#39;s Greenway to the Chesapeake Bay</strong>\n- Download or listen to an \n<a href=\"http://urbantells.net/gwynnsfalls\">audio tour</a>\non the Gwynns Falls Trail with trail historian \nEd Orser and audio artist Steve Bradley.</p>\n"}, :link=>{:href=>nil, :content=>"Baltimore Greenway to the Chesapeake Bay"}, :by_line=>{:content=>""}, :edit_button=>{:href=>"/admin/articles/17/edit", :content=>"Edit this Article", :class=>[[:class, nil, [[:insert, "button", []], [:insert, "radius", []], [:insert, "success", []]]]]}, :id_and_title=>{:content=>"17 - Baltimore Greenway to the Chesapeake Bay"}, :body_length=>{:content=>215}, :show_link=>{:href=>"/articles/17", :content=>"Show"}, :edit_link=>{:href=>"/admin/articles/17/edit", :content=>"Edit"}, :remove_link=>{:href=>"/admin/articles/17", :content=>"Remove", "data-confirm"=>"Are you sure?", "data-method"=>"delete"}, :_root=>{:view=>[]}}], []]], :channel=>:"scope:article;mutation:list"}

**Comment by bryanp** [comment]
Still wrapping my head around this, but here are instructions for inserting a class on a view:

```ruby
[[:attrs, nil, [:class, nil, [:insert, :foo_class, []]]]]
```

We want the instructions coming out of the binder to be as close to this as possible, but it just isn't possible for them to match completely because the instructions emerge from the binder nested among the data rather than as nested instructions. I don't think there's a way around that.

Here's the message @jphager2 posted distilled down into the important bits:

```ruby
[:apply, [{
  edit_button: {
    href: '/admin/articles/17/edit',
    content: '...',
    class: [[:class, nil, [:insert, :button, []], [:insert, :radius, []], [:insert, :success, []]]]
  }
}]]
```

Something that comes to mind is supporting this:

```ruby
[:apply, [{
  edit_button: {
    _attrs: {
      href: '/admin/articles/17/edit',
      class: [
        [:insert, :button, []], 
        [:insert, :radius, []], 
        [:insert, :success, []]
      ]
    },
    _content: '...'
  }
}]]
```

On the JS side, we'd execute everything under `_attrs` inside of an attributes context, and of course handle `_content` the way we do currently. I'll continue thinking about it but maybe this is enough to take a next step on?

**Pull request closed without merging**
